### ISSUE TITLE
Software failure during boot on 1.9.0 beta 2

### ISSUE THREAD

**Issue by robdaemon** [mntmn/amiga2000-gfxcard#5]
After updating to the 1.9.0b2 firmware (Tested both the Z2 75 mhz clock 2 mb mode, and Z2 100 mhz clock firmwares) and installing the new drivers, I get a software failure on startup:

FILE0
Program failed (error #80000006)
Suspend / Reboot

My configuration:
Amiga 2000
A2630 with BigRAM 2630
Buddha IDE
VA2000 + VA2000CX

I did not see this error with the 1.9.0b2 firmware and 1.8.5 driver combination.

**Comment by robdaemon** [comment]
Okay, this is a false alarm. Somehow one of my device driver files in Devs:DOSDrivers got corrupted. It just appeared when I rebooted immediately after updating the VA2000 drivers.

**Comment by mntmn** [comment]
Ahh, thanks for the clarification. This is exactly what I suspected.

Cheers
Lukas
